### ISSUE TITLE
 #0 faild to run error="undefined method `request_uri' for #<URI::Generic:0x007f46cde98110>" error_class="NoMethodError"

### ISSUE THREAD

**Issue by texag93** [niyonmaruz/fluent-plugin-jmx#6]
Hi,

I am testing out this plugin to see if it will work for us. I am using the sample config.

```
<source>
  @type jmx
  tag jmx.memory
  url slc07gxg.us.oracle.com:9111
  mbean java.lang:type=Memory
  attribute HeapMemoryUsage
  interval 60
  inner_path used
</source>
```

When I restart the td-agent, I see this error in the log.

```2019-02-26 16:31:28 +0000 [info]: Received graceful stop
2019-02-26 16:31:29 +0000 [info]: #0 fluentd worker is now stopping worker=0
2019-02-26 16:31:29 +0000 [info]: #0 shutting down fluentd worker worker=0
2019-02-26 16:31:29 +0000 [info]: #0 shutting down input plugin type=:jmx plugin_id="object:3fa36805062c"
2019-02-26 16:31:29 +0000 [info]: #0 shutting down output plugin type=:copy plugin_id="object:3fa36809f9ac"
2019-02-26 16:31:30 +0000 [info]: #0 shutting down output plugin type=:elasticsearch plugin_id="object:3fa36806444c"
2019-02-26 16:31:30 +0000 [info]: #0 shutting down output plugin type=:stdout plugin_id="object:3fa3683dca20"
2019-02-26 16:31:30 +0000 [info]: Worker 0 finished with status 0
2019-02-26 16:31:33 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2019-02-26 16:31:33 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type jmx
    tag "jmx.memory"
    url "slc07gxg.us.oracle.com:9111"
    mbean "java.lang:type=Memory"
    attribute "HeapMemoryUsage"
    interval 60
    inner_path "used"
  </source>
  <match *.**>
    @type stdout
  </match>
</ROOT>
2019-02-26 16:31:33 +0000 [info]: starting fluentd-1.3.3 pid=15908 ruby="2.4.0"
2019-02-26 16:31:33 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--use-v1-config", "--group", "td-agent", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.2.0'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.12.5'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.2'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-jmx' version '0.0.5'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-kafka' version '0.5.0'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-mongo' version '1.2.1'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.8'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-s3' version '1.0.0.rc1'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-td' version '0.10.29'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2019-02-26 16:31:34 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2019-02-26 16:31:34 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-02-26 16:31:34 +0000 [info]: gem 'fluentd' version '1.2.6'
2019-02-26 16:31:34 +0000 [info]: gem 'fluentd' version '0.14.11'
2019-02-26 16:31:34 +0000 [info]: adding match pattern="*.**" type="stdout"
2019-02-26 16:31:34 +0000 [info]: adding source type="jmx"
2019-02-26 16:31:34 +0000 [info]: #0 starting fluentd worker pid=15918 ppid=15913 worker=0
2019-02-26 16:31:34 +0000 [info]: #0 fluentd worker is now running worker=0
2019-02-26 16:31:34.301657170 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2019-02-26 16:32:34 +0000 [error]: #0 faild to run error="undefined method `request_uri' for #<URI::Generic:0x007fa051bd96a8>" error_class="NoMethodError"
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-jmx-0.0.5/lib/fluent/plugin/in_jmx.rb:60:in `block in _get_record'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:608:in `start'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-jmx-0.0.5/lib/fluent/plugin/in_jmx.rb:59:in `_get_record'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-jmx-0.0.5/lib/fluent/plugin/in_jmx.rb:44:in `execute'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-02-26 16:32:34 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-02-26 16:32:34.303694058 +0000 fluent.error: {"error":"undefined method `request_uri' for #<URI::Generic:0x007fa051bd96a8>","error_class":"NoMethodError","message":"faild to run error=\"undefined method `request_uri' for #<URI::Generic:0x007fa051bd96a8>\" error_class=\"NoMethodError\""}
```

**Comment by texag93** [comment]
The MBean server is WebLogic 12c.

**Comment by niyonmaruz** [comment]
Hi, Thank you for asking. I'm going to check that.
